# Generated by Django 4.2.3 on 2023-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('keyword', models.TextField()),
                ('keyword_en', models.TextField(null=True)),
                ('keyword_ru', models.TextField(null=True)),
                ('keyword_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
