# Generated by Django 4.2.3 on 2023-07-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fieldmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(through='users.ProductFieldValue', to='users.fieldmodel')),
            ],
        ),
        migrations.AddField(
            model_name='productfieldvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.productmodel'),
        ),
    ]
