# Generated by Django 4.2.3 on 2023-07-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fieldmodel_productfieldvalue_productmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfieldvalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='productfieldvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='fields',
        ),
        migrations.DeleteModel(
            name='FieldModel',
        ),
        migrations.DeleteModel(
            name='ProductFieldValue',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
