name: PROJECT CD

on:
  push:
    branches: [master]

jobs:
  test:
    services:
      postgres:
        image: postgres:14.8
        env:
          POSTGRES_DB: portfolio
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: root.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Install requirements
        run: pip3 install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: connect and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: test.cebilonsuvfiltr.uz
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd portfolio_drf/
            git pull
            sudo systemctl restart gunicorn.socket gunicorn.service